apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: podinfo
  namespace: ocm-system
spec:
  interval: 10m0s
  component: github.com/acme/podinfo
  version:
    semver: "v3.0.0"
  repository:
    url: ghcr.io/Skarlso
    secretRef:
      name: creds
  verify:
  - name: alice
    publicKey:
      secretRef:
        name: alice-publickey
